// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RpcRequest.proto
// Protobuf Java Version: 4.29.3

package lilac.rpcframework.remote.proto;

public final class RpcRequestProto {
  private RpcRequestProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      RpcRequestProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RpcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:lilac.rpcframework.remote.proto.RpcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string request_id = 1;</code>
     * @return The requestId.
     */
    java.lang.String getRequestId();
    /**
     * <code>string request_id = 1;</code>
     * @return The bytes for requestId.
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <code>string service_name = 2;</code>
     * @return The serviceName.
     */
    java.lang.String getServiceName();
    /**
     * <code>string service_name = 2;</code>
     * @return The bytes for serviceName.
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>string method_name = 3;</code>
     * @return The methodName.
     */
    java.lang.String getMethodName();
    /**
     * <code>string method_name = 3;</code>
     * @return The bytes for methodName.
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>repeated .google.protobuf.Any parameters = 4;</code>
     */
    java.util.List<com.google.protobuf.Any> 
        getParametersList();
    /**
     * <code>repeated .google.protobuf.Any parameters = 4;</code>
     */
    com.google.protobuf.Any getParameters(int index);
    /**
     * <code>repeated .google.protobuf.Any parameters = 4;</code>
     */
    int getParametersCount();
    /**
     * <code>repeated .google.protobuf.Any parameters = 4;</code>
     */
    java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getParametersOrBuilderList();
    /**
     * <code>repeated .google.protobuf.Any parameters = 4;</code>
     */
    com.google.protobuf.AnyOrBuilder getParametersOrBuilder(
        int index);

    /**
     * <code>repeated string param_types = 5;</code>
     * @return A list containing the paramTypes.
     */
    java.util.List<java.lang.String>
        getParamTypesList();
    /**
     * <code>repeated string param_types = 5;</code>
     * @return The count of paramTypes.
     */
    int getParamTypesCount();
    /**
     * <code>repeated string param_types = 5;</code>
     * @param index The index of the element to return.
     * @return The paramTypes at the given index.
     */
    java.lang.String getParamTypes(int index);
    /**
     * <code>repeated string param_types = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paramTypes at the given index.
     */
    com.google.protobuf.ByteString
        getParamTypesBytes(int index);

    /**
     * <code>string version = 6;</code>
     * @return The version.
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 6;</code>
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>string group = 7;</code>
     * @return The group.
     */
    java.lang.String getGroup();
    /**
     * <code>string group = 7;</code>
     * @return The bytes for group.
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <code>string fully_expose_name = 8;</code>
     * @return The fullyExposeName.
     */
    java.lang.String getFullyExposeName();
    /**
     * <code>string fully_expose_name = 8;</code>
     * @return The bytes for fullyExposeName.
     */
    com.google.protobuf.ByteString
        getFullyExposeNameBytes();

    /**
     * <code>string return_type = 9;</code>
     * @return The returnType.
     */
    java.lang.String getReturnType();
    /**
     * <code>string return_type = 9;</code>
     * @return The bytes for returnType.
     */
    com.google.protobuf.ByteString
        getReturnTypeBytes();
  }
  /**
   * Protobuf type {@code lilac.rpcframework.remote.proto.RpcRequest}
   */
  public static final class RpcRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:lilac.rpcframework.remote.proto.RpcRequest)
      RpcRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        RpcRequest.class.getName());
    }
    // Use RpcRequest.newBuilder() to construct.
    private RpcRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RpcRequest() {
      requestId_ = "";
      serviceName_ = "";
      methodName_ = "";
      parameters_ = java.util.Collections.emptyList();
      paramTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      version_ = "";
      group_ = "";
      fullyExposeName_ = "";
      returnType_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lilac.rpcframework.remote.proto.RpcRequestProto.internal_static_lilac_rpcframework_remote_proto_RpcRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lilac.rpcframework.remote.proto.RpcRequestProto.internal_static_lilac_rpcframework_remote_proto_RpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest.class, lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest.Builder.class);
    }

    public static final int REQUEST_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object requestId_ = "";
    /**
     * <code>string request_id = 1;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <code>string request_id = 1;</code>
     * @return The bytes for requestId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICE_NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object serviceName_ = "";
    /**
     * <code>string service_name = 2;</code>
     * @return The serviceName.
     */
    @java.lang.Override
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      }
    }
    /**
     * <code>string service_name = 2;</code>
     * @return The bytes for serviceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_NAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object methodName_ = "";
    /**
     * <code>string method_name = 3;</code>
     * @return The methodName.
     */
    @java.lang.Override
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>string method_name = 3;</code>
     * @return The bytes for methodName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMETERS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<com.google.protobuf.Any> parameters_;
    /**
     * <code>repeated .google.protobuf.Any parameters = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.Any> getParametersList() {
      return parameters_;
    }
    /**
     * <code>repeated .google.protobuf.Any parameters = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getParametersOrBuilderList() {
      return parameters_;
    }
    /**
     * <code>repeated .google.protobuf.Any parameters = 4;</code>
     */
    @java.lang.Override
    public int getParametersCount() {
      return parameters_.size();
    }
    /**
     * <code>repeated .google.protobuf.Any parameters = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Any getParameters(int index) {
      return parameters_.get(index);
    }
    /**
     * <code>repeated .google.protobuf.Any parameters = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getParametersOrBuilder(
        int index) {
      return parameters_.get(index);
    }

    public static final int PARAM_TYPES_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList paramTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string param_types = 5;</code>
     * @return A list containing the paramTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getParamTypesList() {
      return paramTypes_;
    }
    /**
     * <code>repeated string param_types = 5;</code>
     * @return The count of paramTypes.
     */
    public int getParamTypesCount() {
      return paramTypes_.size();
    }
    /**
     * <code>repeated string param_types = 5;</code>
     * @param index The index of the element to return.
     * @return The paramTypes at the given index.
     */
    public java.lang.String getParamTypes(int index) {
      return paramTypes_.get(index);
    }
    /**
     * <code>repeated string param_types = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the paramTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getParamTypesBytes(int index) {
      return paramTypes_.getByteString(index);
    }

    public static final int VERSION_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object version_ = "";
    /**
     * <code>string version = 6;</code>
     * @return The version.
     */
    @java.lang.Override
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 6;</code>
     * @return The bytes for version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUP_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object group_ = "";
    /**
     * <code>string group = 7;</code>
     * @return The group.
     */
    @java.lang.Override
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      }
    }
    /**
     * <code>string group = 7;</code>
     * @return The bytes for group.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FULLY_EXPOSE_NAME_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fullyExposeName_ = "";
    /**
     * <code>string fully_expose_name = 8;</code>
     * @return The fullyExposeName.
     */
    @java.lang.Override
    public java.lang.String getFullyExposeName() {
      java.lang.Object ref = fullyExposeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fullyExposeName_ = s;
        return s;
      }
    }
    /**
     * <code>string fully_expose_name = 8;</code>
     * @return The bytes for fullyExposeName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFullyExposeNameBytes() {
      java.lang.Object ref = fullyExposeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullyExposeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RETURN_TYPE_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object returnType_ = "";
    /**
     * <code>string return_type = 9;</code>
     * @return The returnType.
     */
    @java.lang.Override
    public java.lang.String getReturnType() {
      java.lang.Object ref = returnType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        returnType_ = s;
        return s;
      }
    }
    /**
     * <code>string return_type = 9;</code>
     * @return The bytes for returnType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReturnTypeBytes() {
      java.lang.Object ref = returnType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        returnType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, requestId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serviceName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, serviceName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(methodName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, methodName_);
      }
      for (int i = 0; i < parameters_.size(); i++) {
        output.writeMessage(4, parameters_.get(i));
      }
      for (int i = 0; i < paramTypes_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, paramTypes_.getRaw(i));
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, version_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(group_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, group_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fullyExposeName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, fullyExposeName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(returnType_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 9, returnType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, requestId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serviceName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, serviceName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(methodName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, methodName_);
      }
      for (int i = 0; i < parameters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, parameters_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < paramTypes_.size(); i++) {
          dataSize += computeStringSizeNoTag(paramTypes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParamTypesList().size();
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(version_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, version_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(group_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, group_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(fullyExposeName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, fullyExposeName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(returnType_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(9, returnType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest)) {
        return super.equals(obj);
      }
      lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest other = (lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest) obj;

      if (!getRequestId()
          .equals(other.getRequestId())) return false;
      if (!getServiceName()
          .equals(other.getServiceName())) return false;
      if (!getMethodName()
          .equals(other.getMethodName())) return false;
      if (!getParametersList()
          .equals(other.getParametersList())) return false;
      if (!getParamTypesList()
          .equals(other.getParamTypesList())) return false;
      if (!getVersion()
          .equals(other.getVersion())) return false;
      if (!getGroup()
          .equals(other.getGroup())) return false;
      if (!getFullyExposeName()
          .equals(other.getFullyExposeName())) return false;
      if (!getReturnType()
          .equals(other.getReturnType())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + SERVICE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getServiceName().hashCode();
      hash = (37 * hash) + METHOD_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      if (getParametersCount() > 0) {
        hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
        hash = (53 * hash) + getParametersList().hashCode();
      }
      if (getParamTypesCount() > 0) {
        hash = (37 * hash) + PARAM_TYPES_FIELD_NUMBER;
        hash = (53 * hash) + getParamTypesList().hashCode();
      }
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
      hash = (37 * hash) + FULLY_EXPOSE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFullyExposeName().hashCode();
      hash = (37 * hash) + RETURN_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getReturnType().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code lilac.rpcframework.remote.proto.RpcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:lilac.rpcframework.remote.proto.RpcRequest)
        lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lilac.rpcframework.remote.proto.RpcRequestProto.internal_static_lilac_rpcframework_remote_proto_RpcRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lilac.rpcframework.remote.proto.RpcRequestProto.internal_static_lilac_rpcframework_remote_proto_RpcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest.class, lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest.Builder.class);
      }

      // Construct using lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        requestId_ = "";
        serviceName_ = "";
        methodName_ = "";
        if (parametersBuilder_ == null) {
          parameters_ = java.util.Collections.emptyList();
        } else {
          parameters_ = null;
          parametersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        paramTypes_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        version_ = "";
        group_ = "";
        fullyExposeName_ = "";
        returnType_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lilac.rpcframework.remote.proto.RpcRequestProto.internal_static_lilac_rpcframework_remote_proto_RpcRequest_descriptor;
      }

      @java.lang.Override
      public lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest getDefaultInstanceForType() {
        return lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest.getDefaultInstance();
      }

      @java.lang.Override
      public lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest build() {
        lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest buildPartial() {
        lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest result = new lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest result) {
        if (parametersBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            parameters_ = java.util.Collections.unmodifiableList(parameters_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.parameters_ = parameters_;
        } else {
          result.parameters_ = parametersBuilder_.build();
        }
      }

      private void buildPartial0(lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.requestId_ = requestId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.serviceName_ = serviceName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.methodName_ = methodName_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          paramTypes_.makeImmutable();
          result.paramTypes_ = paramTypes_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.version_ = version_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.group_ = group_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.fullyExposeName_ = fullyExposeName_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.returnType_ = returnType_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest) {
          return mergeFrom((lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest other) {
        if (other == lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getServiceName().isEmpty()) {
          serviceName_ = other.serviceName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (parametersBuilder_ == null) {
          if (!other.parameters_.isEmpty()) {
            if (parameters_.isEmpty()) {
              parameters_ = other.parameters_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureParametersIsMutable();
              parameters_.addAll(other.parameters_);
            }
            onChanged();
          }
        } else {
          if (!other.parameters_.isEmpty()) {
            if (parametersBuilder_.isEmpty()) {
              parametersBuilder_.dispose();
              parametersBuilder_ = null;
              parameters_ = other.parameters_;
              bitField0_ = (bitField0_ & ~0x00000008);
              parametersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getParametersFieldBuilder() : null;
            } else {
              parametersBuilder_.addAllMessages(other.parameters_);
            }
          }
        }
        if (!other.paramTypes_.isEmpty()) {
          if (paramTypes_.isEmpty()) {
            paramTypes_ = other.paramTypes_;
            bitField0_ |= 0x00000010;
          } else {
            ensureParamTypesIsMutable();
            paramTypes_.addAll(other.paramTypes_);
          }
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getGroup().isEmpty()) {
          group_ = other.group_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (!other.getFullyExposeName().isEmpty()) {
          fullyExposeName_ = other.fullyExposeName_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (!other.getReturnType().isEmpty()) {
          returnType_ = other.returnType_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                requestId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                serviceName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                methodName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                com.google.protobuf.Any m =
                    input.readMessage(
                        com.google.protobuf.Any.parser(),
                        extensionRegistry);
                if (parametersBuilder_ == null) {
                  ensureParametersIsMutable();
                  parameters_.add(m);
                } else {
                  parametersBuilder_.addMessage(m);
                }
                break;
              } // case 34
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureParamTypesIsMutable();
                paramTypes_.add(s);
                break;
              } // case 42
              case 50: {
                version_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                group_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                fullyExposeName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                returnType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object requestId_ = "";
      /**
       * <code>string request_id = 1;</code>
       * @return The requestId.
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string request_id = 1;</code>
       * @return The bytes for requestId.
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string request_id = 1;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        requestId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string request_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        requestId_ = getDefaultInstance().getRequestId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string request_id = 1;</code>
       * @param value The bytes for requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        requestId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object serviceName_ = "";
      /**
       * <code>string service_name = 2;</code>
       * @return The serviceName.
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string service_name = 2;</code>
       * @return The bytes for serviceName.
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string service_name = 2;</code>
       * @param value The serviceName to set.
       * @return This builder for chaining.
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        serviceName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string service_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceName() {
        serviceName_ = getDefaultInstance().getServiceName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string service_name = 2;</code>
       * @param value The bytes for serviceName to set.
       * @return This builder for chaining.
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        serviceName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>string method_name = 3;</code>
       * @return The methodName.
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string method_name = 3;</code>
       * @return The bytes for methodName.
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method_name = 3;</code>
       * @param value The methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        methodName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string method_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethodName() {
        methodName_ = getDefaultInstance().getMethodName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string method_name = 3;</code>
       * @param value The bytes for methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        methodName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.Any> parameters_ =
        java.util.Collections.emptyList();
      private void ensureParametersIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          parameters_ = new java.util.ArrayList<com.google.protobuf.Any>(parameters_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> parametersBuilder_;

      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public java.util.List<com.google.protobuf.Any> getParametersList() {
        if (parametersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(parameters_);
        } else {
          return parametersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public int getParametersCount() {
        if (parametersBuilder_ == null) {
          return parameters_.size();
        } else {
          return parametersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public com.google.protobuf.Any getParameters(int index) {
        if (parametersBuilder_ == null) {
          return parameters_.get(index);
        } else {
          return parametersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public Builder setParameters(
          int index, com.google.protobuf.Any value) {
        if (parametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParametersIsMutable();
          parameters_.set(index, value);
          onChanged();
        } else {
          parametersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public Builder setParameters(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (parametersBuilder_ == null) {
          ensureParametersIsMutable();
          parameters_.set(index, builderForValue.build());
          onChanged();
        } else {
          parametersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public Builder addParameters(com.google.protobuf.Any value) {
        if (parametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParametersIsMutable();
          parameters_.add(value);
          onChanged();
        } else {
          parametersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public Builder addParameters(
          int index, com.google.protobuf.Any value) {
        if (parametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParametersIsMutable();
          parameters_.add(index, value);
          onChanged();
        } else {
          parametersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public Builder addParameters(
          com.google.protobuf.Any.Builder builderForValue) {
        if (parametersBuilder_ == null) {
          ensureParametersIsMutable();
          parameters_.add(builderForValue.build());
          onChanged();
        } else {
          parametersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public Builder addParameters(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (parametersBuilder_ == null) {
          ensureParametersIsMutable();
          parameters_.add(index, builderForValue.build());
          onChanged();
        } else {
          parametersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public Builder addAllParameters(
          java.lang.Iterable<? extends com.google.protobuf.Any> values) {
        if (parametersBuilder_ == null) {
          ensureParametersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, parameters_);
          onChanged();
        } else {
          parametersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public Builder clearParameters() {
        if (parametersBuilder_ == null) {
          parameters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          parametersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public Builder removeParameters(int index) {
        if (parametersBuilder_ == null) {
          ensureParametersIsMutable();
          parameters_.remove(index);
          onChanged();
        } else {
          parametersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public com.google.protobuf.Any.Builder getParametersBuilder(
          int index) {
        return getParametersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public com.google.protobuf.AnyOrBuilder getParametersOrBuilder(
          int index) {
        if (parametersBuilder_ == null) {
          return parameters_.get(index);  } else {
          return parametersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
           getParametersOrBuilderList() {
        if (parametersBuilder_ != null) {
          return parametersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(parameters_);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public com.google.protobuf.Any.Builder addParametersBuilder() {
        return getParametersFieldBuilder().addBuilder(
            com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public com.google.protobuf.Any.Builder addParametersBuilder(
          int index) {
        return getParametersFieldBuilder().addBuilder(
            index, com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any parameters = 4;</code>
       */
      public java.util.List<com.google.protobuf.Any.Builder> 
           getParametersBuilderList() {
        return getParametersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getParametersFieldBuilder() {
        if (parametersBuilder_ == null) {
          parametersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  parameters_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          parameters_ = null;
        }
        return parametersBuilder_;
      }

      private com.google.protobuf.LazyStringArrayList paramTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureParamTypesIsMutable() {
        if (!paramTypes_.isModifiable()) {
          paramTypes_ = new com.google.protobuf.LazyStringArrayList(paramTypes_);
        }
        bitField0_ |= 0x00000010;
      }
      /**
       * <code>repeated string param_types = 5;</code>
       * @return A list containing the paramTypes.
       */
      public com.google.protobuf.ProtocolStringList
          getParamTypesList() {
        paramTypes_.makeImmutable();
        return paramTypes_;
      }
      /**
       * <code>repeated string param_types = 5;</code>
       * @return The count of paramTypes.
       */
      public int getParamTypesCount() {
        return paramTypes_.size();
      }
      /**
       * <code>repeated string param_types = 5;</code>
       * @param index The index of the element to return.
       * @return The paramTypes at the given index.
       */
      public java.lang.String getParamTypes(int index) {
        return paramTypes_.get(index);
      }
      /**
       * <code>repeated string param_types = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the paramTypes at the given index.
       */
      public com.google.protobuf.ByteString
          getParamTypesBytes(int index) {
        return paramTypes_.getByteString(index);
      }
      /**
       * <code>repeated string param_types = 5;</code>
       * @param index The index to set the value at.
       * @param value The paramTypes to set.
       * @return This builder for chaining.
       */
      public Builder setParamTypes(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParamTypesIsMutable();
        paramTypes_.set(index, value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string param_types = 5;</code>
       * @param value The paramTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParamTypes(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParamTypesIsMutable();
        paramTypes_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string param_types = 5;</code>
       * @param values The paramTypes to add.
       * @return This builder for chaining.
       */
      public Builder addAllParamTypes(
          java.lang.Iterable<java.lang.String> values) {
        ensureParamTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, paramTypes_);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string param_types = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearParamTypes() {
        paramTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string param_types = 5;</code>
       * @param value The bytes of the paramTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParamTypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureParamTypesIsMutable();
        paramTypes_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 6;</code>
       * @return The version.
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 6;</code>
       * @return The bytes for version.
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 6;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        version_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        version_ = getDefaultInstance().getVersion();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string version = 6;</code>
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        version_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object group_ = "";
      /**
       * <code>string group = 7;</code>
       * @return The group.
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string group = 7;</code>
       * @return The bytes for group.
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string group = 7;</code>
       * @param value The group to set.
       * @return This builder for chaining.
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        group_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string group = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroup() {
        group_ = getDefaultInstance().getGroup();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string group = 7;</code>
       * @param value The bytes for group to set.
       * @return This builder for chaining.
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        group_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private java.lang.Object fullyExposeName_ = "";
      /**
       * <code>string fully_expose_name = 8;</code>
       * @return The fullyExposeName.
       */
      public java.lang.String getFullyExposeName() {
        java.lang.Object ref = fullyExposeName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fullyExposeName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fully_expose_name = 8;</code>
       * @return The bytes for fullyExposeName.
       */
      public com.google.protobuf.ByteString
          getFullyExposeNameBytes() {
        java.lang.Object ref = fullyExposeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fullyExposeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fully_expose_name = 8;</code>
       * @param value The fullyExposeName to set.
       * @return This builder for chaining.
       */
      public Builder setFullyExposeName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fullyExposeName_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string fully_expose_name = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearFullyExposeName() {
        fullyExposeName_ = getDefaultInstance().getFullyExposeName();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string fully_expose_name = 8;</code>
       * @param value The bytes for fullyExposeName to set.
       * @return This builder for chaining.
       */
      public Builder setFullyExposeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fullyExposeName_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private java.lang.Object returnType_ = "";
      /**
       * <code>string return_type = 9;</code>
       * @return The returnType.
       */
      public java.lang.String getReturnType() {
        java.lang.Object ref = returnType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          returnType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string return_type = 9;</code>
       * @return The bytes for returnType.
       */
      public com.google.protobuf.ByteString
          getReturnTypeBytes() {
        java.lang.Object ref = returnType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          returnType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string return_type = 9;</code>
       * @param value The returnType to set.
       * @return This builder for chaining.
       */
      public Builder setReturnType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        returnType_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>string return_type = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearReturnType() {
        returnType_ = getDefaultInstance().getReturnType();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>string return_type = 9;</code>
       * @param value The bytes for returnType to set.
       * @return This builder for chaining.
       */
      public Builder setReturnTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        returnType_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:lilac.rpcframework.remote.proto.RpcRequest)
    }

    // @@protoc_insertion_point(class_scope:lilac.rpcframework.remote.proto.RpcRequest)
    private static final lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest();
    }

    public static lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcRequest>
        PARSER = new com.google.protobuf.AbstractParser<RpcRequest>() {
      @java.lang.Override
      public RpcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RpcRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RpcRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public lilac.rpcframework.remote.proto.RpcRequestProto.RpcRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lilac_rpcframework_remote_proto_RpcRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lilac_rpcframework_remote_proto_RpcRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020RpcRequest.proto\022\037lilac.rpcframework.r" +
      "emote.proto\032\031google/protobuf/any.proto\"\332" +
      "\001\n\nRpcRequest\022\022\n\nrequest_id\030\001 \001(\t\022\024\n\014ser" +
      "vice_name\030\002 \001(\t\022\023\n\013method_name\030\003 \001(\t\022(\n\n" +
      "parameters\030\004 \003(\0132\024.google.protobuf.Any\022\023" +
      "\n\013param_types\030\005 \003(\t\022\017\n\007version\030\006 \001(\t\022\r\n\005" +
      "group\030\007 \001(\t\022\031\n\021fully_expose_name\030\010 \001(\t\022\023" +
      "\n\013return_type\030\t \001(\tB2\n\037lilac.rpcframewor" +
      "k.remote.protoB\017RpcRequestProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_lilac_rpcframework_remote_proto_RpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lilac_rpcframework_remote_proto_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_lilac_rpcframework_remote_proto_RpcRequest_descriptor,
        new java.lang.String[] { "RequestId", "ServiceName", "MethodName", "Parameters", "ParamTypes", "Version", "Group", "FullyExposeName", "ReturnType", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
